import type { LucideIcon, LucideProps } from 'lucide-react'
import {
  Activity,
  AirVent,
  AlarmClock,
  Armchair,
  Backpack,
  BadgeCheck,
  Banknote,
  Bath,
  BedDouble,
  Bell,
  Bike,
  BookOpen,
  Bus,
  Briefcase,
  Building,
  Building2,
  CakeSlice,
  Calendar,
  Camera,
  Car,
  Cat,
  CircleDollarSign,
  ClipboardList,
  CloudRain,
  Coffee,
  Coins,
  Compass,
  CookingPot,
  CreditCard,
  Croissant,
  Droplets,
  Dumbbell,
  Film,
  Flower2,
  Fuel,
  Gamepad2,
  Gift,
  GlassWater,
  Globe,
  GraduationCap,
  Hammer,
  Headphones,
  HeartPulse,
  Home,
  Hotel,
  House,
  Laptop,
  Landmark,
  Lamp,
  Lightbulb,
  MapPinned,
  Milk,
  Monitor,
  MoonStar,
  Music,
  Newspaper,
  Palette,
  PawPrint,
  PenTool,
  Phone,
  PiggyBank,
  Pizza,
  Pill,
  Plane,
  Popcorn,
  Receipt,
  Rocket,
  Sandwich,
  School,
  Scissors,
  ShieldCheck,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingBasket,
  ShoppingCart,
  Smartphone,
  Soup,
  Sparkles,
  Sprout,
  Store,
  Sun,
  Tent,
  Ticket,
  TrainFront,
  TramFront,
  Trash2,
  Trees,
  TrendingUp,
  Trophy,
  Tv,
  Umbrella,
  Utensils,
  Wallet,
  WashingMachine,
  Watch,
  Waves,
  Wifi,
  Wine,
  Wrench,
} from 'lucide-react'

export const CATEGORY_ICON_OPTIONS: ReadonlyArray<{
  key: string
  label: string
  component: LucideIcon
}> = [
  { key: 'activity', label: 'Activity', component: Activity },
  { key: 'air-vent', label: 'Air Vent', component: AirVent },
  { key: 'alarm-clock', label: 'Alarm', component: AlarmClock },
  { key: 'armchair', label: 'Armchair', component: Armchair },
  { key: 'backpack', label: 'Backpack', component: Backpack },
  { key: 'badge-check', label: 'Verified', component: BadgeCheck },
  { key: 'banknote', label: 'Banknote', component: Banknote },
  { key: 'bath', label: 'Bath', component: Bath },
  { key: 'bed-double', label: 'Bedroom', component: BedDouble },
  { key: 'bell', label: 'Alerts', component: Bell },
  { key: 'bike', label: 'Bike', component: Bike },
  { key: 'book-open', label: 'Books', component: BookOpen },
  { key: 'briefcase', label: 'Briefcase', component: Briefcase },
  { key: 'building', label: 'Building', component: Building },
  { key: 'building-2', label: 'Office', component: Building2 },
  { key: 'bus', label: 'Bus', component: Bus },
  { key: 'cake-slice', label: 'Dessert', component: CakeSlice },
  { key: 'calendar', label: 'Calendar', component: Calendar },
  { key: 'camera', label: 'Camera', component: Camera },
  { key: 'car', label: 'Car', component: Car },
  { key: 'cat', label: 'Pets', component: Cat },
  { key: 'circle-dollar-sign', label: 'Currency', component: CircleDollarSign },
  { key: 'clipboard-list', label: 'Bills', component: ClipboardList },
  { key: 'cloud-rain', label: 'Weather', component: CloudRain },
  { key: 'home', label: 'Home', component: Home },
  { key: 'lamp', label: 'Lamp', component: Lamp },
  { key: 'wrench', label: 'Wrench', component: Wrench },
  { key: 'droplets', label: 'Utilities', component: Droplets },
  { key: 'utensils', label: 'Utensils', component: Utensils },
  { key: 'coffee', label: 'Coffee', component: Coffee },
  { key: 'coins', label: 'Coins', component: Coins },
  { key: 'compass', label: 'Compass', component: Compass },
  { key: 'cooking-pot', label: 'Cooking', component: CookingPot },
  { key: 'credit-card', label: 'Card', component: CreditCard },
  { key: 'croissant', label: 'Bakery', component: Croissant },
  { key: 'dumbbell', label: 'Fitness', component: Dumbbell },
  { key: 'film', label: 'Film', component: Film },
  { key: 'flower-2', label: 'Flowers', component: Flower2 },
  { key: 'shopping-bag', label: 'Shopping', component: ShoppingBag },
  { key: 'pizza', label: 'Pizza', component: Pizza },
  { key: 'fuel', label: 'Fuel', component: Fuel },
  { key: 'plane', label: 'Plane', component: Plane },
  { key: 'glass-water', label: 'Water', component: GlassWater },
  { key: 'globe', label: 'Global', component: Globe },
  { key: 'heart-pulse', label: 'Health', component: HeartPulse },
  { key: 'pill', label: 'Pill', component: Pill },
  { key: 'hammer', label: 'Repair', component: Hammer },
  { key: 'headphones', label: 'Audio', component: Headphones },
  { key: 'hotel', label: 'Hotel', component: Hotel },
  { key: 'house', label: 'House', component: House },
  { key: 'laptop', label: 'Laptop', component: Laptop },
  { key: 'landmark', label: 'Bank', component: Landmark },
  { key: 'lightbulb', label: 'Ideas', component: Lightbulb },
  { key: 'map-pinned', label: 'Location', component: MapPinned },
  { key: 'milk', label: 'Groceries', component: Milk },
  { key: 'monitor', label: 'Monitor', component: Monitor },
  { key: 'moon-star', label: 'Night', component: MoonStar },
  { key: 'ticket', label: 'Ticket', component: Ticket },
  { key: 'gamepad-2', label: 'Gamepad', component: Gamepad2 },
  { key: 'music', label: 'Music', component: Music },
  { key: 'tv', label: 'TV', component: Tv },
  { key: 'newspaper', label: 'News', component: Newspaper },
  { key: 'palette', label: 'Design', component: Palette },
  { key: 'paw-print', label: 'Animals', component: PawPrint },
  { key: 'pen-tool', label: 'Creative', component: PenTool },
  { key: 'phone', label: 'Phone', component: Phone },
  { key: 'piggy-bank', label: 'Savings', component: PiggyBank },
  { key: 'trending-up', label: 'Growth', component: TrendingUp },
  { key: 'popcorn', label: 'Cinema', component: Popcorn },
  { key: 'receipt', label: 'Receipt', component: Receipt },
  { key: 'rocket', label: 'Launch', component: Rocket },
  { key: 'sandwich', label: 'Sandwich', component: Sandwich },
  { key: 'school', label: 'School', component: School },
  { key: 'scissors', label: 'Salon', component: Scissors },
  { key: 'gift', label: 'Gift', component: Gift },
  { key: 'graduation-cap', label: 'Education', component: GraduationCap },
  { key: 'shield-check', label: 'Insurance', component: ShieldCheck },
  { key: 'ship', label: 'Ship', component: Ship },
  { key: 'shirt', label: 'Clothing', component: Shirt },
  { key: 'shopping-basket', label: 'Basket', component: ShoppingBasket },
  { key: 'shopping-cart', label: 'Cart', component: ShoppingCart },
  { key: 'smartphone', label: 'Mobile', component: Smartphone },
  { key: 'soup', label: 'Soup', component: Soup },
  { key: 'sparkles', label: 'Beauty', component: Sparkles },
  { key: 'sprout', label: 'Garden', component: Sprout },
  { key: 'store', label: 'Store', component: Store },
  { key: 'sun', label: 'Sunny', component: Sun },
  { key: 'tent', label: 'Camping', component: Tent },
  { key: 'train-front', label: 'Train', component: TrainFront },
  { key: 'tram-front', label: 'Metro', component: TramFront },
  { key: 'trash-2', label: 'Trash', component: Trash2 },
  { key: 'trees', label: 'Nature', component: Trees },
  { key: 'trophy', label: 'Achievement', component: Trophy },
  { key: 'umbrella', label: 'Protection', component: Umbrella },
  { key: 'wallet', label: 'Wallet', component: Wallet },
  { key: 'washing-machine', label: 'Laundry', component: WashingMachine },
  { key: 'watch', label: 'Watch', component: Watch },
  { key: 'waves', label: 'Waterfront', component: Waves },
  { key: 'wifi', label: 'Internet', component: Wifi },
  { key: 'wine', label: 'Wine', component: Wine },
]

const iconMap = Object.fromEntries(
  CATEGORY_ICON_OPTIONS.map((icon) => [icon.key, icon.component]),
) as Record<string, LucideIcon>

export function renderCategoryIcon(
  iconName: string | null | undefined,
  props?: LucideProps,
) {
  const IconComponent = iconName ? iconMap[iconName] : undefined
  const ResolvedIcon = IconComponent ?? ShoppingBag
  return <ResolvedIcon {...props} />
}

export function getCategoryIconLabel(iconName: string | null | undefined) {
  return CATEGORY_ICON_OPTIONS.find((icon) => icon.key === iconName)?.label ?? 'Category'
}
