# Project Name
spring.application.name=financeTracker

# ===============================
# DATABASE CONNECTION (PostgreSQL)
# ===============================
# Default port for Postgres is 5432. Database name is personalTracker.
spring.datasource.url=jdbc:postgresql://localhost:5432/personalTracker
spring.datasource.username=postgres
spring.datasource.password=rootvijay
spring.datasource.driverClassName=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE SETTINGS
# ===============================
# 'update' automatically creates/updates tables in Postgres based on your Java code
spring.jpa.hibernate.ddl-auto=update

# Shows the SQL queries in the console (very helpful for debugging)
spring.jpa.show-sql=true

# Standard dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# SERVER SETTINGS
# ===============================
# Default port is 8080. If your frontend needs a different port, you can change it here.
server.port=8080
spring.devtools.restart.enabled=true