name: Build and deploy Node.js app to Azure Web App - finance-frontand

on:
  push:
    branches:
      - version1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        # Corrected path to find your package.json
        working-directory: "Personal Finance Tracker/frontand/personal-tracker-app"
        
        # INJECTING BOTH VARIABLES HERE
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
          VITE_APP_BASE_URL: ${{ vars.VITE_APP_BASE_URL }}
          
        run: |
          npm install
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          # Vite puts files in 'dist'. We point to that specific folder.
          path: "Personal Finance Tracker/frontand/personal-tracker-app/dist/"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_5CF11400833B479D9223A64B4445AFE3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_75C771BD4FB7420E854C2F587B171DB9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_74335A58E85E48AB9F20AAF7A0A1E64B }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'finance-frontand'
          slot-name: 'Production'
          package: .
